### Create a new meal
POST http://192.168.1.17:5000/meals
Content-Type: application/json

{
  "title": "Lunch",
  "date": "2025-03-12T12:00:00",
  "foods": []
}

### Get all meals
GET http://192.168.1.17:5000/meals

### Get a meal by ID
GET http://192.168.1.17:5000/meals/39d36bdc-4e91-4576-9075-a1827fb3f847

### Update a meal
PUT http://192.168.1.17:5000/meals/39d36bdc-4e91-4576-9075-a1827fb3f847
Content-Type: application/json

{
  "title": "Dinner 44",
  "date": "2025-03-12T18:00:00",
  "foods": [
    {
      "id": "96f339ed-2eea-4719-a68b-1bae1ad4efd1",
      "quantity": 3
    },
    {
      "id": "1c9f8f6d-690e-4a6c-a8ea-d4a3feff4dfa",
      "quantity": 5
    },
    {
      "id": "b771c7a5-2ae2-4d0a-857e-d17d96ead7e5",
      "quantity": 7
    }
  ]
}

### Delete a meal
DELETE http://192.168.1.17:5000/meals/e15ae25a-d460-4643-8cbd-d16ca30acf80